### ISSUE TITLE
Plugin doesn't load

### ISSUE THREAD

**Issue by OVNSAME** [PluginSmiths/Creating-addons-support#4]
It's critical bug. Something wrong with categories or procedures. We don't have lots of information about it, but we knows that something missed or returns null.

Log:
_2024-09-28-18:56:45 [Application-Loader/DEBUG] [Blockly JavaScript Files loader] Loading Blockly JavaScript files from plugins
2024-09-28-18:56:45 [Application-Loader/DEBUG] [Blockly Toolboxes loader] Loading Blockly toolboxes from plugins
2024-09-28-18:56:45 [Application-Loader/DEBUG] [Blockly loader] Loading blocks for procedures
2024-09-28-18:56:45 [Application-Loader/ERROR] [Exception] Uncaught exception in Application-Loader
java.lang.NullPointerException: Cannot invoke "java.lang.Comparable.compareTo(Object)" because the return value of "java.util.function.Function.apply(Object)" is null
	at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:473) ~[?:?]
	at java.base/java.util.TimSort.binarySort(TimSort.java:296) ~[?:?]
	at java.base/java.util.TimSort.sort(TimSort.java:239) ~[?:?]
	at java.base/java.util.Arrays.sort(Arrays.java:1307) ~[?:?]
	at java.base/java.util.ArrayList.sort(ArrayList.java:1721) ~[?:?]
	at net.mcreator.blockly.data.ExternalBlockLoader.<init>(ExternalBlockLoader.java:119) ~[mcreator.exe:?]
	at net.mcreator.blockly.data.BlocklyLoader.addBlockLoader(BlocklyLoader.java:81) ~[mcreator.exe:?]
	at net.mcreator.blockly.data.BlocklyLoader.<init>(BlocklyLoader.java:68) ~[mcreator.exe:?]
	at net.mcreator.blockly.data.BlocklyLoader.init(BlocklyLoader.java:33) ~[mcreator.exe:?]
	at net.mcreator.ui.MCreatorApplication.lambda$new$4(MCreatorApplication.java:149) ~[mcreator.exe:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
_

**Comment by AxoIsAxo** [comment]
may you used the wrong mcreator version

**Comment by OVNSAME** [comment]
No, I used one of supported versions of the plugin.
